In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/survey.csv')
schema_df = pd.read_csv('../data/schema.csv')

In [3]:
pd.set_option('display.max_column', 150)
pd.set_option('display.max_rows', 150)

In [4]:
df.head(10)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
5,6,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online...",NaN,NaN,10,NaN,Student,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Cloud Firestore,Cloud Firestore,Cloud Firestore,Cloudflare,Cloudflare,Cloudflare,Node.js,Node.js,Node.js,Rasberry Pi,Rasberry Pi,Rasberry Pi,NaN,NaN,NaN,Docker;Homebrew;npm;Pip;pnpm,Homebrew;npm;Pip;pnpm,Homebrew;npm;Pip;pnpm,Nano;Vim;Visual Studio Code;Xcode,Nano;Vim;Visual Studio Code;Xcode,Nano;Vim;Visual Studio Code;Xcode,iOS;MacOS;Ubuntu,NaN,Markdown File,Markdown File,Markdown File,Discord,Discord,Discord,ChatGPT;GitHub Copilot;OpenAI Codex,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Debugging and getting help,Documenting code;Testing code;Committing and r...,Learning about a codebase;Project planning,NaN,Writing code;Debugging and getting help,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
6,7,"I am not primarily a developer, but I write co...",35-44 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Written...,NaN,7,7,Academic researcher,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,R,R,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RStudio,RStudio,RStudio,MacOS,MacOS,NaN,NaN,NaN,Microsoft Teams;Whatsapp,Microsoft Teams;Whatsapp,Microsoft Teams;Whatsapp,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
7,8,I am learning to code,18-24 years old,"Student, full-time;Not employed, but looking f...",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Video-based Online Cou...,First-party knowledge base,1,NaN,Student,NaN,NaN,NaN,NaN,NaN,Uzbekistan,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,Supabase,Supabase,Supabase,Firebase;Netlify;Vercel,Vercel,Vercel,Next.js;React,Next.js;React,Next.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Vite;Yarn,npm;Vite,npm;Vite,Visual Studio Code,Visual Studio Code,Visual Studio Code,MacOS,MacOS,Jira,NaN,NaN,Google Meet;Telegram;Zoom,Google Meet;Telegram,Google Meet;Telegram,ChatGPT,ChatGPT,ChatGPT,Stack Overflow,Less than once per month or monthly,No,NaN,Quickly finding code solutions;Finding reliabl...,"No, not at all",Yes,Indifferent,Increase productivity;Speed up learning;Improv...,Somewhat distrust,Bad at handling complex tasks,Writing code;Debugging and getting help;Search...,Project planning;Testing code,NaN,NaN,NaN,Writing code;Debugging and getting help;Search...,NaN,NaN,Yes,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,NaN,NaN
8,9,I code primarily as a hobby,45-54 years old,"Employed, full-time",In-person,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Other online resources ...,Stack Overflow;Written-based Online Courses,NaN,20,NaN,Academic researcher,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Lua,Lua,Lua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Studio Code,Visual Studio Code,Visual Studio Code,MacOS,MacOS,NaN,NaN,NaN,Skype,Skype,Skype,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Engage with community by commenting on questio...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
9,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,Traditional public search engine;AI-powered se...,15,11,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Serbia,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,MongoDB;MySQL;PostgreSQL;Redis,MongoDB;MySQL;PostgreSQL;Redis,MongoDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Digital Ocean;Fireba...,Amazon Web Services (AWS);Digital Ocean;Fireba...,Amazon Web Services (AWS);Digital Ocean;Fireba...,Express;Next.js;Node.js;React,Express;Next.js;Node.js;React,Express;Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Webpack,npm;Webpack,npm;Webpack,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,Windows,Jira,Jira,Jira,Discord;Google Meet;Skype;Slack,Discord;Google Meet;Skype;Slack,Discord;Google Meet;Skype;Slack,ChatGPT;Google Gemini,ChatGPT;Google Gemini,ChatGPT;Google Gemini,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions,"Yes, somewhat",Yes,Indifferent,Increase productivity;Speed up learning,Neither trust nor distrust,Bad at handling complex tasks,Search for answers,NaN,NaN,NaN,Search for answers,NaN,NaN,NaN,I'm not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN

In [5]:
df['MainBranch']  #printing any one column. This is preferable in case the the df.function has the same name as column name. e.g if there is column name 'count', ti conflicts with df method count

0        I am a developer by profession
1        I am a developer by profession
2        I am a developer by profession
3                 I am learning to code
4        I am a developer by profession
                      ...
65432    I am a developer by profession
65433    I am a developer by profession
65434    I am a developer by profession
65435    I am a developer by profession
65436       I code primarily as a hobby
Name: MainBranch, Length: 65437, dtype: str

In [6]:
df.MainBranch

0        I am a developer by profession
1        I am a developer by profession
2        I am a developer by profession
3                 I am learning to code
4        I am a developer by profession
                      ...
65432    I am a developer by profession
65433    I am a developer by profession
65434    I am a developer by profession
65435    I am a developer by profession
65436       I code primarily as a hobby
Name: MainBranch, Length: 65437, dtype: str

In [7]:
type(df['MainBranch'])

pandas.Series

In [9]:
df[['MainBranch','Age','Employment']] #printing more than once column of the DataFrame

                           MainBranch                 Age           Employment
0      I am a developer by profession  Under 18 years old  Employed, full-time
1      I am a developer by profession     35-44 years old  Employed, full-time
2      I am a developer by profession     45-54 years old  Employed, full-time
3               I am learning to code     18-24 years old   Student, full-time
4      I am a developer by profession     18-24 years old   Student, full-time
...                               ...                 ...                  ...
65432  I am a developer by profession     18-24 years old  Employed, full-time
65433  I am a developer by profession     25-34 years old  Employed, full-time
65434  I am a developer by profession     25-34 years old  Employed, full-time
65435  I am a developer by profession     18-24 years old  Employed, full-time
65436     I code primarily as a hobby     18-24 years old   Student, full-time

[65437 rows x 3 columns]

In [10]:
df.columns #prints all the columns

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       ...
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9',
       'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
       'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=114)

In [11]:
df.iloc[0]

ResponseId                                                                        1
MainBranch                                           I am a developer by profession
Age                                                              Under 18 years old
Employment                                                      Employed, full-time
RemoteWork                                                                   Remote
Check                                                                        Apples
CodingActivities                                                              Hobby
EdLevel                                                   Primary/elementary school
LearnCode                                                    Books / Physical media
LearnCodeOnline                                                                 NaN
TechDoc                                                                         NaN
YearsCode                                                                       NaN
YearsCodePro                                                                    NaN
DevType                                                                         NaN
OrgSize                                                                         NaN
PurchaseInfluence                                                               NaN
BuyNewTool                                                                      NaN
BuildvsBuy                                                                      NaN
TechEndorse                                                                     NaN
Country                                                    United States of America
Currency                                                                        NaN
CompTotal                                                                       NaN
LanguageHaveWorkedWith                                                          NaN
LanguageWantToWorkWith                                                          NaN
LanguageAdmired                                                                 NaN
DatabaseHaveWorkedWith                                                          NaN
DatabaseWantToWorkWith                                                          NaN
DatabaseAdmired                                                                 NaN
PlatformHaveWorkedWith                                                          NaN
PlatformWantToWorkWith                                                          NaN
PlatformAdmired                                                                 NaN
WebframeHaveWorkedWith                                                          NaN
WebframeWantToWorkWith                                                          NaN
WebframeAdmired                                                                 NaN
EmbeddedHaveWorkedWith                                                          NaN
EmbeddedWantToWorkWith                                                          NaN
EmbeddedAdmired                                                                 NaN
MiscTechHaveWorkedWith                                                          NaN
MiscTechWantToWorkWith                                                          NaN
MiscTechAdmired                                                                 NaN
ToolsTechHaveWorkedWith                                                         NaN
ToolsTechWantToWorkWith                                                         NaN
ToolsTechAdmired                                                                NaN
NEWCollabToolsHaveWorkedWith                                                    NaN
NEWCollabToolsWantToWorkWith                                                    NaN
NEWCollabToolsAdmired                                                           NaN
OpSysPersonal use                                                               NaN
OpSysProfessional use                                                           NaN
OfficeStackAsyncHaveWorkedWith                                                  NaN
OfficeStackAsyncWantToWorkWith                                                  NaN
OfficeStackAsyncAdmired                                                         NaN
OfficeStackSyncHaveWorkedWith                                                   NaN
OfficeStackSyncWantToWorkWith                                                   NaN
OfficeStackSyncAdmired                                                          NaN
AISearchDevHaveWorkedWith                                                       NaN
AISearchDevWantToWorkWith                                                       NaN
AISearchDevAdmired                                                              NaN
NEWSOSites                        I have never visited Stack Overflow or the Sta...
SOVisitFreq                                                                     NaN
SOAccount                                                                       NaN
SOPartFreq                                                                      NaN
SOHow                                                                           NaN
SOComm                                                                          NaN
AISelect                                                                        Yes
AISent                                                               Very favorable
AIBen                                                         Increase productivity
AIAcc                                                                           NaN
AIComplex                                                                       NaN
AIToolCurrently Using                                                           NaN
AIToolInterested in Using                                                       NaN
AIToolNot interested in Using                                                   NaN
AINextMuch more integrated                                                      NaN
AINextNo change                                                                 NaN
AINextMore integrated                                                           NaN
AINextLess integrated                                                           NaN
AINextMuch less integrated                                                      NaN
AIThreat                                                                        NaN
AIEthics                                                                        NaN
AIChallenges                                                                    NaN
TBranch                                                                          No
ICorPM                                                                          NaN
WorkExp                                                                         NaN
Knowledge_1                                                                     NaN
Knowledge_2                                                                     NaN
Knowledge_3                                                                     NaN
Knowledge_4                                                                     NaN
Knowledge_5                                                                     NaN
Knowledge_6                                                                     NaN
Knowledge_7                                                                     NaN
Knowledge_8                                                                     NaN
Knowledge_9                                                                     NaN
Frequency_1                                                                     NaN
Frequency_2                                                                     NaN
Frequency_3                                                                     NaN
TimeSearching                                                                   NaN
TimeAnswering                                                                   NaN
Frustration                                                                     NaN
ProfessionalTech                                                                NaN
ProfessionalCloud                                                               NaN
ProfessionalQuestion                                                            NaN
Industry                                                                        NaN
JobSatPoints_1                                                                  NaN
JobSatPoints_4                                                                  NaN
JobSatPoints_5                                                                  NaN
JobSatPoints_6                                                                  NaN
JobSatPoints_7                                                                  NaN
JobSatPoints_8                                                                  NaN
JobSatPoints_9                                                                  NaN
JobSatPoints_10                                                                 NaN
JobSatPoints_11                                                                 NaN
SurveyLength                                                                    NaN
SurveyEase                                                                      NaN
ConvertedCompYearly                                                             NaN
JobSat                                                                          NaN
Name: 0, dtype: object

In [12]:
df.iloc[[0,1]]  #printing more than one specified number of rows

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

In [13]:
df.loc[[0,1], ['MainBranch', 'Age', 'Employment']]    #printing the specified rows and specified columns

                       MainBranch                 Age           Employment
0  I am a developer by profession  Under 18 years old  Employed, full-time
1  I am a developer by profession     35-44 years old  Employed, full-time

In [14]:
df['MainBranch'].value_counts()       #counts the number of distinct values

MainBranch
I am a developer by profession                                                           50207
I am not primarily a developer, but I write code sometimes as part of my work/studies     6511
I am learning to code                                                                     3875
I code primarily as a hobby                                                               3334
I used to be a developer by profession, but no longer am                                  1510
Name: count, dtype: int64

In [16]:
df.loc[0, 'RemoteWork']              #return the value for column 'RemoteWork' in row number 0

'Remote'

In [17]:
df.loc[[0,1,2], 'RemoteWork']        #return the value of the specified column for multiple rows

0    Remote
1    Remote
2    Remote
Name: RemoteWork, dtype: str

In [18]:
df.loc[0:2, 'RemoteWork']            #we can also pass the slice of the rows

0    Remote
1    Remote
2    Remote
Name: RemoteWork, dtype: str

In [19]:
df.loc[0:2, 'MainBranch':'Check']    #We can pass the slice of rows and slice of columns

,MainBranch,Age,Employment,RemoteWork,Check
0,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples
1,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples
2,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples